### ISSUE TITLE
gsplus.sh fails to compile on rpi4

### ISSUE THREAD

**Issue by FollyMaddy** [valerino/RetroPie-Setup#13]
The package "libreadline-dev" should be added as dependancy in gsplus.sh to fix the problem.

Issue is described from here :

https://retropie.org.uk/forum/topic/25576/new-scriptmodules-lr-vice-xvic-gsplus-proper-lr-mess-integration/295

Solution is posted from here :

https://retropie.org.uk/forum/topic/25576/new-scriptmodules-lr-vice-xvic-gsplus-proper-lr-mess-integration/305

**Comment by valerino** [comment]
fixed here: https://github.com/valerino/RetroPie-Setup/commit/f52cd075ee1b813f7383234a6f1a17c4ab6d3da9
